services:
  - type: web
    name: shree-financial-llm
    runtime: docker
    plan: free
    dockerCommand: bash render_start.sh
    envVars:
      - key: PORT
        value: "8501"
      - key: OPENAI_API_KEY
        value: ""
